<script lang="ts">
    const games = [
    "ITEM",
    "Risk of Rain 2",
    "Sekiro: Shadows Die Twice (Rest of World)",
    "Five Nights at Freddy's: Help Wanted 2",
    "８番出口",
    "Lethal Company",
    "The Binding of Isaac: Afterbirth",
    "The Binding of Isaac: Repentance",
    "The Binding of Isaac: Afterbirth+",
    "The Binding of Isaac: Rebirth",
    "Layers of Fear",
    "Life is Strange Remastered Collection",
    "Watch_Dogs2",
    "It Takes Two",
    "Inscryption",
    "The Stanley Parable: Ultra Deluxe",
    "Emily Wants to Play Too",
    "Far Cry 5 - Standard Edition",
    "Sid Meier's Civilization VI",
    "Emily Wants To Play",
    "Tabletop Simulator",
    "Metro Exodus (Regular Ed. - Post Launch)",
    "The Last of Us™ Part I",
    "Five Nights at Freddy's: Security Breach - Ruin",
    "Civ V DLC Babylon",
    "Civilization V",
    "Sid Meier's Civilization V: Scrambled Nations Map Pack",
    "Changing Worlds Map Pack: Continents",
    "Sid Meier's Civilization V: Brave New World",
    "Call of Duty&reg;: Black Ops III - Zombies Chronicles Edition (RoW)",
    "Escape the Backrooms",
    "Civ V Gods and Kings Expansion",
    "Civ V Wonders of the Ancient DLC",
    "Civ V Korea DLC",
    "Civilization V: Explorers Map Pack DLC",
    "Civ V Cradle of Civilization Denmark DLC",
    "Civ V DLC - Polynesia",
    "Civ V DLC Double Civ Pack",
    "Call of Duty - Black Ops II",
    "Civ V Cradle DLC: Mesopotamia",
    "Civ V Cradle DLC: Mediterranean",
    "Civ V Cradle DLC: Asia",
    "Civ V Cradle DLC: Americas",
    "Assetto Corsa",
    "Forza Horizon 5 - Standard Edition",
    "The Walking Dead: A New Frontier",
    "The Walking Dead Season 2",
    "Plants vs. Zombies™ Garden Warfare 2: Deluxe Edition",
    "Mighty Fling",
    "Poppy Playtime - Multiplayer",
    "Raft",
    "The Jackbox Party Pack 5",
    "VTOL VR",
    "Injustice™ 2",
    "Gang Beasts",
    "Five Nights at Freddy's: Help Wanted",
    "Ballsmack",
    "INSIDE",
    "MultiVersus",
    "Retail Royale",
    "Geometry Dash",
    "RecRoom",
    "A Dance of Fire and Ice",
    "Fears to Fathom - Episode 1",
    "PUBG: BATTLEGROUNDS",
    "tModLoader",
    "Outlast 2",
    "RISK: Global Domination",
    "The Jackbox Party Pack 8",
    "DRAGON BALL XENOVERSE",
    "The Wolf Among Us",
    "Super Seducer",
    "Golf With Your Friends",
    "Twelve Minutes",
    "JUMP FORCE",
    "Uno",
    "Keep Talking and Nobody Explodes",
    "Don't Starve",
    "Undertale",
    "Five Nights at Freddy's: Security Breach",
    "Portal 2",
    "The Lab (Bundle-only)",
    "Condition Zero",
    "Day of Defeat: Source",
    "Team Fortress Classic",
    "Day of Defeat",
    "Deathmatch Classic",
    "Half-Life: Opposing Force",
    "Ricochet",
    "Half-Life",
    "Half-Life: Blue Shift",
    "Half-Life 2",
    "Counter-Strike: Source",
    "Half-Life 1: Source",
    "Half-Life 2: Episode One",
    "Portal",
    "Half-Life 2: Episode Two",
    "Left 4 Dead",
    "Don't Starve Together",
    "Saints Row: The Third - The Full Package",
    "American Truck Simulator",
    "Euro Truck Simulator 2",
    "Halo Infinite",
    "Deep Rock Galactic",
    "DOOM Eternal Standard Edition",
    "DOOM",
    "Crab Game",
    "Murder House",
    "The Walking Dead",
    "Tomb Raider",
    "The Room",
    "The Room 4: Old Sins",
    "The Walking Dead: The Final Season",
    "Rust",
    "RESIDENT EVIL 7",
    "Friday the 13th: The Game",
    "The Room Three",
    "The Room Two",
    "Outlast",
    "The Forest",
    "RESIDENT EVIL 3",
    "Dishonored (ROW)",
    "PAYDAY 2",
    "Dying Light Enhanced Edition ROW",
    "Halo: The Master Chief Collection",
    "Bioshock Infinite (WW)",
    "Borderlands 2 ROW",
    "The Sims™ 4",
    "Assassin's Creed Odyssey - Standard Edition",
    "Assassin's Creed Origins - Standard Edition",
    "Subnautica",
    "Batman: Arkham Collection",
    "Mortal Kombat 11",
    "DRAGON BALL XENOVERSE 2",
    "DRAGON BALL FighterZ",
    "DRAGON BALL Z: KAKAROT",
    "Amnesia: The Dark Descent",
    "Minion Masters - Mordar’s Malediction Limited Free Promotional Package - Sep 2021",
    "Sea of Thieves 2023 Edition",
    "Fall Guys",
    "Red Dead Redemption 2",
    "Hunt: Showdown",
    "No Man's Sky",
    "Dead by Daylight",
    "Bloons TD 6",
    "The Witcher 2",
    "The Witcher 3: Wild Hunt",
    "The Witcher: Enhanced Edition",
    "Fallout: New Vegas",
    "Muck",
    "Five Nights at Freddy's",
    "RESIDENT EVIL 2 / BIOHAZARD RE:2 Standard Edition",
    "Doki Doki Literature Club",
    "EVE Online",
    "RuneScape",
    "Warframe",
    "Destiny 2",
    "Apex Legends",
    "Tom Clancy's Rainbow Six Siege",
    "Wallpaper Engine",
    "Life is Strange 2 - Episode 1",
    "Paladins",
    "Life is Strange Episode 1",
    "H1Z1",
    "Unturned",
    "Left 4 Dead 2",
    "Phasmophobia",
    "Among Us",
    "Layers of Fear (2016)",
    "SCP: Secret Laboratory",
    "Counter-Strike: Global Offensive Free Edition",
    "SpaceEngine",
    "VRChat",
    "Brawlhalla Free On Demand",
    "Aimlabs - Free",
    "Quake Champions",
    "Ultimate Custom Night",
    "Terraria",
    "Garry's Mod"
]
    function handleClick() {
        const randomIndex = Math.floor(Math.random() * (games.length))
        const game = games[randomIndex]
        alert(game + "! Play now.")
    }
</script>
<div class="w-full h-screen flex items-center justify-center bg-neutral-900">
    <button class="bg-blue-600 text-white p-2 rounded font-semibold hover:bg-blue-500" on:click={handleClick}>Choose game</button>
</div>